site_name: Compustarter
site_description: Wiki@LitLUG 是由柳州铁树 Linux 用户协会维护的 GNU/Linux Wiki站点
site_author: Editor@Compustarter

repo_name: ImJingLan/Compustarter
repo_url: "https://github.com/ImJingLan/Compustarter"

copyright: Copyright &copy; <a href="https://github.com/ImJingLan/Compustarter">Compustarter</a> 2025. Available freely under the <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/">CC BY-NC-SA 4.0 license</a>.

theme:
  name: material
  language: zh
  logo: assets/img/irontree.svg
  favicon: assets/img/irontree.svg
  palette:
    primary: "white"
    accent: "blue"
  features:
    - navigation.tabs
    - navigation.instant
    - content.code.copy
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.top

markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.superfences
  - markdown.extensions.def_list
  - toc:
      permalink: true

nav:
  - 欢迎: index.md
  - FAQ: faq.md
  - 指南与规则:
      - 格式风格: rules/styleguide.md
  - 软件:
      - Steam: software/steam.md

extra_css:
  - "assets/css/extra-color.css"
  - "assets/css/extra.css"
